using DG.Tweening;

public enum SkyAniDuration
{
	AnimationCurve = Ease.Linear,
	EaseInBack=Ease.InBack,
	EaseInBounce=Ease.InBounce,
	EaseInCirc=Ease.InCirc,
	EaseInCubic=Ease.InCubic,
	EaseInElastic=Ease.InElastic,
	EaseInExpo=Ease.InExpo,
	EaseInOutBack=Ease.InOutBack,
	EaseInOutBounce=Ease.InOutBounce,
	EaseInOutCirc=Ease.InOutCirc,
	EaseInOutCubic=Ease.InOutCubic,
	EaseInOutElastic=Ease.InOutElastic,
	EaseInOutExpo=Ease.InOutExpo,
	EaseInOutQuad=Ease.InOutQuad,
	EaseInOutQuart=Ease.InOutQuart,
	EaseInOutQuint=Ease.InOutQuint,
	EaseInOutSine=Ease.InOutSine,
	EaseInQuad=Ease.InQuad,
	EaseInQuart=Ease.InQuart,
	EaseInQuint=Ease.InQuint,
	EaseInSine=Ease.InSine,
	EaseOutBack=Ease.OutBack,
	EaseOutBounce=Ease.OutBounce,
	EaseOutCirc=Ease.OutCirc,
	EaseOutCubic=Ease.OutCubic,
	EaseOutElastic=Ease.OutElastic,
	EaseOutExpo=Ease.OutExpo,
	EaseOutQuad=Ease.OutQuad,
	EaseOutQuart=Ease.OutQuart,
	EaseOutQuint=Ease.OutQuint,
	EaseOutSine=Ease.OutSine,
	Linear=Ease.Linear
}
